name: Run iOS Unit and UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Build and test
        run: |
          xcodebuild test \
            -scheme PlanningPoker \
            -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=18.4' \
            -enableCodeCoverage YES
