name: Run iOS Unit and UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.1.app

      #- name: Install dependencies
      #  run: |
      #    brew install cocoapods # if needed
      #    pod install # or other setup scripts

      - name: Build and test
        run: |
          xcodebuild test \
            -scheme PlanningPoker \
            -enableCodeCoverage YES
